# Generated by Django 3.0a1 on 2020-05-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
